### PR TITLE
feat: allow running on 32 bits

### PR DESCRIPTION
**Pull request by PerfectLaugh**
For: https://github.com/denoland/deno/pull/11653

### CODE REVIEW

**Review by AaronO — COMMENTED** [review]
As a first high-level review:
1. **I think this can be much simpler**, the transmuting of magic values is somewhat dependant on pointer-size (and v8's underlaying representation) but we don't need to duplicate all that code
2. **This needs to be tested against a full `deno` build** and its test suite, whilst `serde_v8` has its own unit tests that should be sufficient, we should never break `deno` (one reason in favour of moving `serde_v8` back into the `deno` repo)
3. **We need to have clear expectations about x86/32bit support**. I would not be in favour of it being a "tier 1" supported arch, given that it is EndOfLife and not tested/built in CI

@PerfectLaugh What's your end goal ? Are you looking for official 32bit `deno` binaries to be released & maintained or simply the ability to build them yourself ? Or something else altogether ?

**Comment by PerfectLaugh** [comment]
It would be good to be release on official deno, but I don't expect that either.
Deno ABI are built on expectations in 64bits SystemV ABI. Things could break.
At this point, there are no problem in Windows but have problem in Linux. (In rusty_v8)

The main goal is to try to embed the deno into my 32 bits game server. Due to the game server is not owned by me so I couldn't do any changes like converting into 64 bits, likewise.

And, yeah, I guess I will have to refactor my code to let it elegant.

**Comment by AaronO** [comment]
> The main goal is to try to embed the deno into my 32 bits game server. Due to the game server is not owned by me so I couldn't do any changes like converting into 64 bits, likewise.

Can you elaborate on what you mean by "embed" ? Shouldn't x86_64 windows systems be able to run 32bit and x64 binaries. Are you embedding them in the same process ? Do they have to share the same address space ?

I assume if you don't own the game server (code) you can't recombine them to ship them as a single unified binary. If your game server and `deno` are going to run as separate processes and communicate over some kind of IPC, then x64 deno should work.

(Obviously you know your use case much better than we do, but just want to double check, to ensure that there are no viable alternatives, because it's not clear if there's strong 32bit demand besides your use case)

**Comment by PerfectLaugh** [comment]
In my specific situation:
I have a CSGO game server, which allows me to do modification in binary form, but without source code access. So I couldn't compile the game server itself.
But I can load the dll into game server. What I think is load deno into game server as a DLL and do some game modification rules based on deno VM.

**Pull request closed without merging**
